# Generated by Django 5.2.11 on 2026-02-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(blank=True, default='', upload_to='home/covers/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('cover', models.ImageField(blank=True, default='', upload_to='home/covers/%Y/%m/%d/')),
                ('text', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
